## RNA-Seq-PR
## Author - Victor Kalbskopf

## sample metadata file
samples: config/samples.tsv

## Fastq filenames and locations can either be specified in the config/fastq.tsv file. 
## OR if auto: True -
## gzipped fastq files should be stored in the resources/reads/ directory
## If the sample name is Kisumu1 in the samples.tsv file, the paired-end reads 
## should be named Kisumu1_1.fastq.gz, and Kisumu1_2.fastq.gz. 
## Treatment names in samples.tsv should not contain underscores
fastq: 
      table: config/fastq.tsv
      auto: True # set auto if your files follow 

# Dataset name
# Can be anything, will be used to name some main output files
dataset: 'six_nonsiskins'

# Paths for reference files 
ref:
  # Path to genome reference FASTA file
  genome:
        "resources/reference/PlasmoDB-39_PrelictumSGS1-like_Genome.fasta"
  # Path to transcriptome reference FASTA file
  transcriptome:
        "resources/reference/PlasmoDB-39_PrelictumSGS1-like_AnnotatedTranscripts.fasta"
  # Path to GTF annotation file 
  gtf: 
        "resources/reference/PlasmoDB-39_PrelictumSGS1-like.gtf"
  # Path to GFF annotation file
  gff:
        "resources/reference/PlasmoDB-39_PrelictumSGS1-like.gff"
  # SNPeff database name
  snpeffdb:
        "Plasmodium_relictum_gca_900005765"
  # gene names file with gene and transcript names
  genenames:
        "resources/GeneNames.tsv"

# Chromosome names for the appropriate species. 
# Please ensure that these correspond exactly to the reference fasta/gff files. Extra unwanted chromosomes (unplaced contigs) can be ignored. 
# if you need to remove a prefix (Such as "AgamP4_"or "AaegL5_") from a file, use sed - i.e - "sed s/AgamP4_// An.gambiae.fasta > An.gambiae_clean.fasta"
chroms: ['PRELSG_01_v1', 'PRELSG_02_v1', 'PRELSG_03_v1', 'PRELSG_04_v1', 'PRELSG_05_v1', 'PRELSG_06_v1', 'PRELSG_07_v1', 'PRELSG_08_v1', 'PRELSG_09_v1', 'PRELSG_10_v1', 'PRELSG_11_v1', 'PRELSG_12_v1', 'PRELSG_13_v1', 'PRELSG_14_v1', 'PRELSG_API_v1', 'PRELSG_MIT_v1']

qc:
      activate: True

# List of contrasts to do Differential Expression and Fst analysis on. 
# Should correspond to the 'treatment' columns of the samples.tsv file, and be separated by an underscore "_". i.e 'control_case', or 'Kisumu_Tiassale'.
# The treatment names themselves must not contain underscores
contrasts:
      - 'cond1_cond2'
#      - 'cond2_cond3'

# Activate progressiveGenes analysis.
# Will find genes that are consistently up or downregulated across two comparisons. 
# For example - which genes upregulated in Kisumu v gambiaeCont, are also upregulated in gambiaeCont v gambiaePM
progressiveGenes:
      activate: True
      padj_threshold: 0.05
      fc_threshold: 1
      groups: "cond1_cond2"

# Activate fgsea Gene set enrichment analysis 
GSEA:
      activate: False
      gaf: "resources/reference/VectorBase-50_AgambiaePEST_GO.gaf"
      KeggSpeciesID: "aga"            # 3 letter KEGG species identifier. "aga" = Anopheles gambiae/coluzzii. 
      replaceString: "AgaP_"          # An.gambiae KEGG pathways have this string appended which needs removing

# If activate:True, creates allele count .xlsx reports on specific mutations of choice
# Requires appropriate mutations.tsv file
IRmutations: 
      activate: False
      path: "resources/IRmutations.tsv"
      
####                    Variant Calling options                                     #### 
# Ploidy level for freebayes to call at (Generally we are using pooled samples).
# For diploid organisms, this should be 2 * number of individuals in each pool
VariantCalling:
      activate: True
      ploidy: 1
      chunks: 9                # Number of chunks to split each chromosome into when parallelising freebayes. 9 or less is recommended. 

# Activate Population Branch Statistic analysis (Needs three conditions, two closely related and an outgroup)
# This should be tried with other sequencing projects!!
pbs:
      activate: True
      contrasts: 
            - 'cond1_cond2_cond3'
      windownames: ['small', 'large']
      windowsizes: [1000, 5000]
      windowsteps: [500, 1000]
      missingness: 0.5

# For Anopheles gambiae s.l only - run Ancestry Informative Marker analysis.
# AIMs datasets included in git repo
AIMs:
      activate: False
      missingness: 0.5                                # proportion between 0 and 1 
      gambcolu: "resources/gamb_vs_colu.zarr"         # path to gambcolu AIMs
      arab: "resources/gambcolu_vs_arab.zarr"         # path to arab AIMs


# Run analysis with compkaryo to determine proportion % karyotype
karyotype:
        activate: False
        inversions:
             - "2La"
             - "2Rj"
             - "2Rb"
             - "2Rc_col"
             - "2Rc_gam"
             - "2Rd"
             - "2Ru"

# find DE genes that lie under Ag1000g selective sweeps 
sweeps:
      activate: False
      padj_threshold: 0.05
      fc_threshold: 1.5


#### The following modules may not be functional #### 
# Activate differential SNPs analysis with kissde
diffsnps:
        activate: True

# Activate Venn diagram - not working as of v0.3.0
venn:
        activate: False

